<a href="https://colab.research.google.com/github/zhiyuguo-innis/MSSP607/blob/main/zhiyuguo-innis/MSSP607/Modules/Week_4/PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

os.makedirs("Week 4", exist_ok=True)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving parsed.csv to parsed.csv

In [ ]:
import pandas as pd

df = pd.read_csv("parsed.csv")

df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

quetsion a：The 95th percentile of earthquake magnitude in Japan for earthquakes with an mb magnitude type is 4.9.

In [ ]:
japan_mb = df[
    (df["parsed_place"] == "Japan") &
    (df["magType"] == "mb")
]

japan_mb["mag"].quantile(0.95)

np.float64(4.9)

In [ ]:
len(japan_mb)

50

question b: 23.13% of the earthquakes in Indonesia were coupled with tsunamis.

In [ ]:
indonesia = df[df["parsed_place"] == "Indonesia"]

indonesia["tsunami"].mean() * 100

np.float64(23.12925170068027)

In [ ]:
round(indonesia["tsunami"].mean() * 100, 2)

np.float64(23.13)

In [ ]:
indonesia_tsunamis = indonesia["tsunami"].sum()
indonesia_total = len(indonesia)

percentage = indonesia_tsunamis / indonesia_total * 100

print("Total earthquakes:", indonesia_total)
print("Earthquakes with tsunamis:", indonesia_tsunamis)
print("Percentage:", round(percentage, 2), "%")

Total earthquakes: 147
Earthquakes with tsunamis: 34
Percentage: 23.13 %

question c: summary

In [ ]:
nevada = df[df["parsed_place"] == "Nevada"]

In [ ]:
nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [ ]:
nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

question d

In [ ]:
ring_of_fire = [
    "Bolivia",
    "Chile",
    "Ecuador",
    "Peru",
    "Costa Rica",
    "Guatemala",
    "Mexico",
    "Japan",
    "Philippines",
    "Indonesia",
    "New Zealand",
    "Antarctica",
    "Canada",
    "Fiji",
    "Alaska",
    "Washington",
    "California",
    "Russia",
    "Taiwan",
    "Tonga",
    "Kermadec Islands"
]

In [ ]:
df["ring_of_fire"] = df["parsed_place"].isin(ring_of_fire)

In [ ]:
df[["parsed_place", "ring_of_fire"]].head(20)

          parsed_place  ring_of_fire
0           California          True
1           California          True
2           California          True
3           California          True
4           California          True
5   Dominican Republic         False
6               Alaska          True
7           California          True
8           California          True
9            Indonesia          True
10          California          True
11  Dominican Republic         False
12          California          True
13           Indonesia          True
14          California          True
15              Canada          True
16          California          True
17         Puerto Rico         False
18              Alaska          True
19          California          True

question e: Ring of Fire: 7,184 earthquakes Outside Ring of Fire: 2,14

In [ ]:
df["ring_of_fire"].sum()

np.int64(7184)

In [ ]:
(~df["ring_of_fire"]).sum()

np.int64(2148)

question f: There were 45 earthquakes associated with tsunamis along the Ring of Fire.

In [ ]:
ring_of_fire_tsunamis = df[
    (df["ring_of_fire"] == True) &
    (df["tsunami"] == 1)
]

len(ring_of_fire_tsunamis)

45